In [44]:
pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [45]:
import numpy as np

In [46]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [47]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [51]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
np.random.rand(3, 2)

array([[0.38488925, 0.10074805],
       [0.75803073, 0.56779465],
       [0.76376878, 0.19443321]])

In [53]:
np.random.randn(3, 2)

array([[ 0.21704169, -0.84402652],
       [ 1.3498068 , -0.28506659],
       [ 0.44026695, -1.72338539]])

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

2


In [56]:
print(arr.ndim)

2


In [57]:
print(arr.size)

6


In [58]:
print(arr.dtype)

int64


In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [60]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [61]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [62]:
arr.mean()

np.float64(2.5)

In [63]:
arr.max()

np.int64(4)

In [64]:
arr.min()

np.int64(1)

In [65]:
arr.std()

np.float64(1.118033988749895)

In [66]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [67]:
arr[1:4]

array([2, 3, 4])

In [68]:
arr[::2]

array([1, 3, 5])

In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [70]:
arr[:, 1]

array([2, 5])

In [71]:
arr[1, :2]

array([4, 5])

In [72]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [73]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [75]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [76]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [77]:
a = np.array([1, 2, 3])
a + 5 

array([6, 7, 8])